### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE]: The value "NaN" is invalid for option "size"

### ISSUE THREAD

**Issue by chemax** [farhadi/node-smpp#114]
server
https://gist.github.com/77269cfa1c2354e131baa307747e1000
client https://gist.github.com/chemax/84cfb36a88bc9870742a60cd2125a90f
and i have strange error when start this
`chemax@chemax-work:/mnt/c/Users/chemax/projects/hansa/object_12_sms$ node test/client.js
YOUR_SYSTEM_ID YOUR_PASSWORD
PDU {
  command_length: 50,
  command_id: 9,
  command_status: 0,
  sequence_number: 1,
  command: 'bind_transceiver',
  system_id: 'YOUR_SYSTEM_ID',
  password: 'YOUR_PASSWORD',
  system_type: '',
  interface_version: 80,
  addr_ton: 0,
  addr_npi: 0,
  address_range: ''
}
undefined
PDU {
  command_length: 57,
  command_id: 4,
  command_status: 0,
  sequence_number: 2,
  command: 'submit_sm',
  service_type: '',
  source_addr_ton: 0,
  source_addr_npi: 0,
  source_addr: '',
  dest_addr_ton: 0,
  dest_addr_npi: 0,
  destination_addr: 'DESTINATION NUMBER',
  esm_class: 0,
  protocol_id: 0,
  priority_flag: 0,
  schedule_delivery_time: '',
  validity_period: '',
  registered_delivery: 0,
  replace_if_present_flag: 0,
  data_coding: 1,
  sm_default_msg_id: 0,
  short_message: { message: 'Hello!' }
}
RangeError [ERR_INVALID_OPT_VALUE]: The value "NaN" is invalid for option "size"
    at Object.alloc (buffer.js:259:3)
    at PDU._initBuffer (/mnt/c/Users/chemax/projects/hansa/object_12_sms/node_modules/smpp/lib/pdu.js:154:22)
    at PDU.toBuffer (/mnt/c/Users/chemax/projects/hansa/object_12_sms/node_modules/smpp/lib/pdu.js:178:20)
    at Session.send (/mnt/c/Users/chemax/projects/hansa/object_12_sms/node_modules/smpp/lib/smpp.js:97:24)
    at Session.<anonymous> (/mnt/c/Users/chemax/projects/hansa/object_12_sms/app.js:31:21)
    at Session.emit (events.js:203:13)
    at Session._extractPDUs (/mnt/c/Users/chemax/projects/hansa/object_12_sms/node_modules/smpp/lib/smpp.js:67:8)
    at Socket.emit (events.js:203:13)
`
all code from examples. Can you help me, please?

**Comment by chemax** [comment]
Msgid must be STRING.
