### ISSUE TITLE
Crash on submit_sm

### ISSUE THREAD

**Issue by 0LEG0** [farhadi/node-smpp#161]
For testing purposes, I created a transparent smpp proxy. socket A <-> (PDU) <-> socket B.
Here is part of simplest code:
```javascript
a.on("pdu", pdu => {
        console.log("->", pdu);
		
        // Inverse message_id to prevent message_id dublicates
        if (pdu.message_id) pdu.message_id = inverse(pdu.message_id);
        
        // Forward PDU
        console.log("<-", pdu);
        b.send(pdu);
});
```
Everything works fine, but sometimes these death messages happen:
console.log output:
```log
-> PDU {
  command_length: 83,
  command_id: 4,
  command_status: 0,
  sequence_number: 16704908,
  command: 'submit_sm',
  service_type: '',
  source_addr_ton: 5,
  source_addr_npi: 0,
  source_addr: 'aaaa',
  dest_addr_ton: 1,
  dest_addr_npi: 1,
  destination_addr: '0000',
  esm_class: 64,
  protocol_id: 0,
  priority_flag: 0,
  schedule_delivery_time: '',
  validity_period: 2021-01-16T15:32:33.000Z,
  registered_delivery: 1,
  replace_if_present_flag: 0,
  data_coding: 8,
  sm_default_msg_id: 0,
  short_message: { udh: [ <Buffer 00 03 26 02 02> ], message: 'nutes.' }
}
<- PDU {
  command_length: 83,
  command_id: 4,
  command_status: 0,
  sequence_number: 16704908,
  command: 'submit_sm',
  service_type: '',
  source_addr_ton: 5,
  source_addr_npi: 0,
  source_addr: 'aaaa',
  dest_addr_ton: 1,
  dest_addr_npi: 1,
  destination_addr: '0000',
  esm_class: 64,
  protocol_id: 0,
  priority_flag: 0,
  schedule_delivery_time: '',
  validity_period: 2021-01-16T15:32:33.000Z,
  registered_delivery: 1,
  replace_if_present_flag: 0,
  data_coding: 8,
  sm_default_msg_id: 0,
  short_message: { udh: [ <Buffer 00 03 26 02 02> ], message: 'nutes.' }
}
TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be an instance of Buffer or Uint8Array. Received an instance of Array
    at Object.concat (buffer.js:574:13)
    at PDU.encode (/devel/smpp-tools/node_modules/smpp/lib/defs.js:545:17)
    at PDU._filter (/devel/smpp-tools/node_modules/smpp/lib/pdu.js:144:41)
    at PDU.toBuffer (/devel/smpp-tools/node_modules/smpp/lib/pdu.js:177:7)
    at Session.send (/devel/smpp-tools/node_modules/smpp/lib/smpp.js:119:24)
    at Session.<anonymous> (/devel/smpp-tools/proxy.js:90:11)
    at Session.emit (events.js:315:20)
    at Session._extractPDUs (/devel/smpp-tools/node_modules/smpp/lib/smpp.js:88:8)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:569:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
It looks like not correctly decoded-encoded message body.
Here is my ugly workaround preventing proxy from crash but we lost a part of message:
```javascript
a.on("pdu", pdu => {
        console.log("->", pdu);
		
        // Inverse message_id to prevent message_id dublicates
        if (pdu.message_id) pdu.message_id = inverse(pdu.message_id);

        // Ugly workaround
        for (let key in pdu.short_message) {
            if (key !== "message") delete pdu.short_message[key];
        }

        // Forward PDU
        console.log("<-", pdu);
        b.send(pdu);
});
```
I would like to understand the problem, but manipulations with message encoding-decoding are confusing.

**Comment by rmruano** [comment]
I'm not sure about what kind of configuration are you testing. Are you trying to implement some type of relay server? 

client > relay (server & client) > server

Also, could you enable the new debug mode for all clients / servers and post the results? They will be very helpful to try to understand the issue. Debug messages are emitted on the socket level.

**Comment by asepfauji95** [comment]
For forwarding UDH, working well for me.
```

this.reCalculateUDH = (short_message)=>{
    if(short_message.udh){        
        let udhString = JSON.stringify(short_message.udh[0])
        let udhJSON = JSON.parse(udhString)
        let udhData = udhJSON.data
        let sms_count=udhData[3]
        let part_id=udhData[4]
        //This is a unique id present in each message part
        let concat_ref = this.concat_ref++; 
        let udh = new Buffer.alloc(6);

        udh.write(String.fromCharCode(0x5), 0); //Length of UDF
        udh.write(String.fromCharCode(0x0), 1); //Indicator for concatenated message
        udh.write(String.fromCharCode(0x3), 2); //  Subheader Length ( 3 bytes)
        udh.write(String.fromCharCode(concat_ref), 3); //Same reference for all concatenated messages
        udh.write(String.fromCharCode(sms_count), 4); //Number of total messages in the concatenation
        udh.write(String.fromCharCode(part_id), 5); //Sequence number ( used by the mobile to concatenate the split messages)
        return udh
    }else{
        return null
    }    
}
```

**Comment by edgaru** [comment]
```javascript
/**
 * Rebuilds the User Data Header (UDH) for a given short message.
 *
 * @param {Object} short_message - The short message object containing the UDH.
 * @returns {Buffer|null} - The rebuilt UDH as a Buffer, or null if invalid.
 */
function rebuildUDH(short_message) {
    // Initial validation for the existence of UDH and its Information Elements
    if (!short_message?.udh || short_message.udh.length === 0) {
        return null;
    }

    try {
        // Determine if the UDH already includes the UDHL field
        const firstIE = short_message.udh[0];
        const includesUDHL = firstIE && typeof firstIE.readUInt8 === 'function';

        let udh;
        if (includesUDHL) {
            // Assume the first byte already contains UDHL
            udh = Buffer.concat(short_message.udh);
        } else {
            // Calculate the total length of all Information Elements (IEs)
            let totalIEBytes = 0;
            for (const ie of short_message.udh) {
                totalIEBytes += ie.length;
            }

            // Create buffer: 1 byte for User Data Header Length (UDHL) + total bytes of IEs
            udh = Buffer.alloc(1 + totalIEBytes);

            // UDHL: Write the total length of the Information Elements
            udh.writeUInt8(totalIEBytes, 0);

            // Copy each Information Element after the UDHL
            let offset = 1; // Start after the UDHL byte
            for (const ie of short_message.udh) {
                ie.copy(udh, offset);
                offset += ie.length;
            }
        }

        return udh;
    } catch (error) {
        logger.error('Error while rebuilding UDH:', error);
        return null;
    }
}
```
