### ISSUE TITLE
Trying to debug message undefined error

### ISSUE THREAD

**Issue by phil-warner** [farhadi/node-smpp#256]
We've had a handful of uncaught exceptions in our application. The error stack is shown below. It's quite hard to pin it down using the node uncaughtException handler, as we only have access to the error and not the parameters of the request. Does this suggest anything to you guys?

```
TypeError: Cannot read properties of undefined (reading 'message')
at PDU.encode (.../node_modules/smpp/lib/defs.js:371:58)
at PDU._filter (.../node_modules/smpp/lib/pdu.js:141:40)
at PDU.toBuffer (.../node_modules/smpp/lib/pdu.js:160:7)
at Session.send (.../node_modules/smpp/lib/smpp.js:97:24)
at Session.submit_sm (.../node_modules/smpp/lib/smpp.js:130:15)
```

**Comment by fdciabdul** [comment]
This is the non-string `short_message` crash (`Cannot read properties of undefined (reading 'message')`). Fixed in **node-smpp-next** — the encode filter coerces scalars and guards null/undefined (also covers #229), with a regression test.
Fork: https://github.com/fdciabdul/node-smpp-next
