### ISSUE TITLE
Trouble with sending long message in non-ASCII

### ISSUE THREAD

**Issue by qfox** [farhadi/node-smpp#4]
I'm trying to send a long message but something going wrong and I see a stack trace:

```
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at Object.types.buffer.write (/home/qfox/repos/selfcare-tools/node_modules/smpp/lib/defs.js:84:11)
    at PDU.toBuffer (/home/qfox/repos/selfcare-tools/node_modules/smpp/lib/pdu.js:137:20)
    at Session.send (/home/qfox/repos/selfcare-tools/node_modules/smpp/lib/smpp.js:71:24)
    at Session.createShortcut [as submit_sm] (/home/qfox/repos/selfcare-tools/node_modules/smpp/lib/smpp.js:94:15)
    at Object.send (/home/qfox/repos/selfcare-tools/lib/smpp.js:133:24)
    at module.exports.actions.check4g (/home/qfox/repos/selfcare-buddy/routes/api/usim.js:24:14)
    at callbacks (/home/qfox/repos/selfcare-buddy/node_modules/express/lib/router/index.js:164:37)
```

`'Абвгдеёжзий, кл мнопрс туфхцчшщъы ab ьэ юяабв гдеёжзий к лмноп рстуфхцчшщ. ъыьэюяабвгде ёж зийклмнопрст уфхцчшщ ъыьэю: abc.defghi'` is throwing that error while
`'Абвгдеёжзий, кл мнопрс туфхцчшщъы ab ьэ юяабв гдеёжзий к лмноп рстуфхцчшщ. ъыьэюяабвгде ёж зийклмнопрст уфхцчшщ ъыьэю: abc.defg'` is works fine.

Is it a bug or i've just missed something? Thanks.

**Comment by vchatterji** [comment]
Simple Algorithm:
-----------------------
Check if message can be sent using GSM 03.38 charset. Otherwise, assume it's Unicode. You can use 
```
npm install gsm
```
1. If unicode and length < 70 OR if GSM 03.38 and length < 160. Proceed as normal.
3. Otherwise, if unicode, divide message into parts of 67 characters. If GSM 0.38, divide message into parts of 153 characters.
3. Construct UDH for each part as below:
```
//We need to split the message and send it in many parts

//This is a unique id present in each message part
var concat_ref = this.concat_ref++; 

//For GSM 03.38 charset parts
var maxLength = 153; 

//For Unicode char set			
if(info.char_set === "Unicode") {
	maxLength = 67;
}
			
for(var i=0; i<info.sms_count; i++) {
	var part = msg.text.substring(i*maxLength, i*maxLength + maxLength);
	var udh = new Buffer(6);
	udh.write(String.fromCharCode(0x5), 0); //Length of UDH
	udh.write(String.fromCharCode(0x0), 1); //Indicator for concatenated message
	udh.write(String.fromCharCode(0x3), 2); //	Subheader Length ( 3 bytes)
	udh.write(String.fromCharCode(concat_ref), 3); //Same reference for all concatenated messages
	udh.write(String.fromCharCode(info.sms_count), 4); //Number of total messages in the split
	udh.write(String.fromCharCode(i+1), 5); //Sequence number (used by the mobile to concatenate the split messages)
				
	var submit_pdu = {
		source_addr:msg.from,
		destination_addr: msg.to,
		short_message: { udh:udh, message:part },
		registered_delivery:1 //If you want delivery reports
	};
				
	this.getSession().submit_sm(submit_pdu, function(pdu) {
		if (pdu.command_status == 0) {
			console.log("SMPP Gateway[" + this.getOptions().address + "] - SUMBIT[" + submit_pdu.source_addr + ">>>" + submit_pdu.destination_addr + "] - " + pdu.message_id);
		}
	}.bind(this));
}
```

**Comment by dareenzo** [comment]
Questions: Why do String.fromCharCode for these fields? Aren't they supposed to go as hexadecimal values instead of what String.fromCharCode returns?

I ask because, for instance on my PC I get `> String.fromCharCode(0xFF) //=> 'ÿ'` and I don't get why we want to do this.

Thanks in advance
