### ISSUE TITLE
Error while connecting to server with  multi client 

### ISSUE THREAD

**Issue by abdelrahman-mustafa** [farhadi/node-smpp#94]
events.js:167
      throw er; // Unhandled 'error' event
 After following the lib guide with the first connection it works well but after new connection the server throws that error   ^

Error: connect ECONNREFUSED 127.0.0.1:2775
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\dev\Node\New folder\node_modules\smpp\lib\smpp.js:37:8)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by abdelrahman-mustafa** [comment]
when using async/await   the server creation methon will return first session and then cant be accept sessions anymore
